### ISSUE TITLE
Publish it to luarocks for rocks.nvim?

### ISSUE THREAD

**Issue by Freed-Wu** [black-desk/fcitx5-ui.nvim#1]
https://github.com/nvim-neorocks/rocks.nvim can allow user don't declare dependence in package manager.
How about support it?
TIA!

**Comment by black-desk** [comment]
Let me have a look few days later.

**Comment by Freed-Wu** [comment]
Thanks for your reply.

BTW. Is https://github.com/black-desk/fcitx5-ui.nvim/blob/665ecb1365639cd6c14e47f4bacd9121106025a2/lua/fcitx5-ui/init.lua#L6-L12 essential? Because my `~/.local/share/nvim/fcitx5-ui` doesn't exist, and this plugin also work for me.

**Comment by black-desk** [comment]
> Thanks for your reply.
> 
> 
> 
> BTW. Is https://github.com/black-desk/fcitx5-ui.nvim/blob/665ecb1365639cd6c14e47f4bacd9121106025a2/lua/fcitx5-ui/init.lua#L6-L12 essential? Because my `~/.local/share/nvim/fcitx5-ui` doesn't exist, and this plugin also work for me.

check this commit https://github.com/black-desk/fcitx5-ui.nvim/commit/665ecb1365639cd6c14e47f4bacd9121106025a2

**Comment by Freed-Wu** [comment]
> check this commit

Maybe we should add these path only if user install lazy.nvim?
