### ISSUE TITLE
It seems that luarocks do not get updated.

### ISSUE THREAD

**Issue by black-desk** [black-desk/fcitx5-ui.nvim#14]
Github action success.

https://github.com/black-desk/fcitx5-ui.nvim/actions/runs/9617057612/job/26527982673

[logs_25176468782.zip](https://github.com/user-attachments/files/15930679/logs_25176468782.zip)

But rockspec not get updated.

https://luarocks.org/manifests/black-desk/fcitx5-ui.nvim-scm-1.rockspec

```lua
local git_ref = '2612c6cfeb2f31de45a6a7096428ef32f885070e'
local modrev = 'scm'
local specrev = '1'

local repo_url = 'https://github.com/black-desk/fcitx5-ui.nvim'

rockspec_format = '3.0'
package = 'fcitx5-ui.nvim'
version = modrev ..'-'.. specrev

description = {
  summary = 'fcitx5 user interface inside neovim',
  detailed = '',
  labels = { },
  homepage = 'https://github.com/black-desk/fcitx5-ui.nvim',
  license = 'GPL-3.0'
}

dependencies = { 'lua >= 5.1', 'dbus_proxy' } 

test_dependencies = { }

source = {
  url = repo_url .. '/archive/' .. git_ref .. '.zip',
  dir = 'fcitx5-ui.nvim-' .. '2612c6cfeb2f31de45a6a7096428ef32f885070e',
}

if modrev == 'scm' or modrev == 'dev' then
  source = {
    url = repo_url:gsub('https', 'git')
  }
end

build = {
  type = 'builtin',
  copy_directories = { 'doc' } ,
}
```

So what is going on here?

**Comment by black-desk** [comment]
@Freed-Wu

**Comment by Freed-Wu** [comment]
Confused too. Maybe the author of this github action @mrcjkb know it?

**Comment by mrcjkb** [comment]
You have two options: 

- Increment the `specrev` (the number after `scm-`)
- Add a `--force` flag, which you can do with [`extra_luarocks_args`](https://github.com/nvim-neorocks/luarocks-tag-release?tab=readme-ov-file#extra_luarocks_args) input. 

Alternatively, you can just create an scm rockspec that has the git repo as the source, and upload it manually, without using luarocks-tag-release. That way there's no need to update it unless the dependencies change. 
[Here's an example](https://github.com/nvim-neorocks/luarocks-tag-release/blob/master/luarocks-tag-release-scm-1.rockspec).

**Comment by black-desk** [comment]
> You have two options:
> 
> * Increment the `specrev` (the number after `scm-`)
> * Add a `--force` flag, which you can do with [`extra_luarocks_args`](https://github.com/nvim-neorocks/luarocks-tag-release?tab=readme-ov-file#extra_luarocks_args) input.

Should this github actioin failed in this situation?

> 
> Alternatively, you can just create an scm rockspec that has the git repo as the source, and upload it manually, without using luarocks-tag-release. That way there's no need to update it unless the dependencies change. [Here's an example](https://github.com/nvim-neorocks/luarocks-tag-release/blob/master/luarocks-tag-release-scm-1.rockspec?rgh-link-date=2024-06-21T18%3A02%3A19Z).

**Comment by black-desk** [comment]
Fixed.

**Comment by mrcjkb** [comment]
> Should this github actioin failed in this situation?

No, we have a [`fail_on_duplicate`](https://github.com/nvim-neorocks/luarocks-tag-release?tab=readme-ov-file#fail_on_duplicate-optional) option that is `false` by default. 
The reason is that using this workflow to upload scm rockspecs is an unlikely use case, and we want people to be able to run this action on every commit without it failing if a rock already exists.
