### ISSUE TITLE
Activate fcitx5 without startinsert

### ISSUE THREAD

**Issue by Freed-Wu** [black-desk/fcitx5-ui.nvim#2]
https://github.com/black-desk/fcitx5-ui.nvim/blob/master/lua/fcitx5-ui/init.lua#L198

Can we actiavte fcitx5 without startinsert?
Just allow user to do more flexiabler settings: activate fcitx5, do something, startinsert by themselves.

**Comment by black-desk** [comment]
You can send a pull request for features that you want.
